// auth types
export const SET_AUTH_MODAL = "SET_AUTH_MODAL";
export const SET_AUTH_USER_NAME = "SET_AUTH_USER_NAME";
export const SET_AUTH_EMAIL = "SET_AUTH_EMAIL";
export const SET_AUTH_PASSWORD = "SET_AUTH_PASSWORD";
export const SET_AUTH_PHONE_NUMBER = "SET_AUTH_PHONE_NUMBER";
export const SET_AUTH_TETMS_N_CONDITIONS = "SET_AUTH_TETMS_N_CONDITIONS";

// LOADER TYPE
export const LOADER = "LOADER";
export const CATEGORY_LOADER = "CATEGORY_LOADER";

